### ISSUE TITLE
foregroundColor should apply to text in device list

### ISSUE THREAD

**Issue by landlessness** [zettaapi/zetta-starter-app-android#6]
# Overview

A server's `foregroundColor` style property should apply to the text in the device list. Below are screenshots of iPhone and Android.

iPhone has it mostly right. However, I do like that the Android app applies the style info to the server name header like `bangalore` in the screenshot below. So let's keep the styled background color on the server header and just fix the foreground text. I'm going to create a ticket to have iPhone work the same way.
#### Style API

```
{
  "class": [
    "server"
  ],
  "properties": {
    "name": "detroit",
    "style": {
      "foregroundColor": {
        "decimal": {
          "red": 255,
          "green": 255,
          "blue": 255
        },
        "hex": "#FFFFFF"
      },
      "backgroundColor": {
        "decimal": {
          "red": 80,
          "green": 81,
          "blue": 96
        },
        "hex": "#505160"
      }
    }
  }
}
```
#### Android Screenshot

![screenshot_2016-07-12-22-59-27](https://cloud.githubusercontent.com/assets/21422/16790665/b97e752e-4885-11e6-9bcf-189629a9237c.png)
#### iOS Screenshot

![img_3465](https://cloud.githubusercontent.com/assets/21422/16790741/48ffec28-4886-11e6-89ff-0eed5d981826.PNG)
### Android Screenshot

![screenshot_2016-07-12-23-43-39](https://cloud.githubusercontent.com/assets/21422/16791252/1173ecaa-488b-11e6-8cad-c7ad2355f173.png)

**Comment by blundell** [comment]
Fixed (the device text, ignore the rest ;-) ) : 
![screen shot 2016-07-13 at 7 48 28 pm](https://cloud.githubusercontent.com/assets/655860/16815695/cc2cf652-4932-11e6-90cb-62c4ebeec6af.png)
