### ISSUE TITLE
Default app system colors should be neutral

### ISSUE THREAD

**Issue by landlessness** [zettaapi/zetta-starter-app-android#7]
# Overview

The default app system colors should be neutral / grayscale so that the color information coming from the style API won't ever clash. Currently, the settings screen and the empty server screen are blue.

Instead let's have the default system colors be neutral. Below I attached screenshots of iPhone and Android. Let's mimic the iPhone system color approach insofar as we can.
### Android Settings Screen

![screenshot_2016-07-12-23-26-30](https://cloud.githubusercontent.com/assets/21422/16790998/8640a2ce-4888-11e6-9abb-16d1be92379d.png)
### Android Empty Server Screen

![screenshot_2016-07-12-23-26-39](https://cloud.githubusercontent.com/assets/21422/16790999/8641b902-4888-11e6-864b-7bbe0711cb8f.png)
### iPhone Settings Screen

![img_3467](https://cloud.githubusercontent.com/assets/21422/16790921/c789fcd6-4887-11e6-9f72-037e2d4e9e9c.PNG)
### iPhone Empty Server Screen

![img_3466](https://cloud.githubusercontent.com/assets/21422/16790920/c78977f2-4887-11e6-98d5-1df892dbd6e8.PNG)

**Comment by blundell** [comment]
Here we go:
![screen shot 2016-07-13 at 8 14 25 pm](https://cloud.githubusercontent.com/assets/655860/16816596/7f21a4d0-4936-11e6-86a8-c2116a206633.png)

![screen shot 2016-07-13 at 8 09 33 pm](https://cloud.githubusercontent.com/assets/655860/16816482/e8781014-4935-11e6-90fc-5d10424733aa.png)
